feat : 추가 /user/get-user-pk-email
sgdevcamp2022/jikji pull request #49
Opened 2023-02-15 19:59 UTC by 0Chord

### Issue:
- - -
- notification 서버에서 follow서버로 팔로워 목록을 요청할 때 User의 PK를 사용해야 하는데 User의 email밖에 모르므로 Auth-server에 email을 통한 유저 PK발급 API 생성

### 🖇️ 개발 내용
- email로 유저 PK를 발급하는 get-user-pk-email API 개발

2023-02-16 08:51 UTC, mardi2020 commented
조회할때는 post http method보다 get method를 사용합니다~ 그리고 uri는 간단하게 user 리소스로만 표현하시면 될것같아요
자세한 내용은 **REST API** 공부해보시면 도움되실 것 같네요.

2023-02-16 08:55 UTC, mardi2020 requested changes
코멘트에 달아놓았습니다

2023-02-16 09:39 UTC, 0Chord commented
다시 변경완료 했습니다!

2023-02-19 12:13 UTC, JeonghyeonK approved these changes
수고하셨습니다~

2023-02-19 12:14 UTC, JeonghyeonK approved these changes
수고하셨습니다~

2023-02-20 16:29 UTC, closed without merging